
IF OBJECT_ID( N'[dbo].[TABLE_BOAT]' , N'U' ) IS NULL
BEGIN
	CREATE TABLE [dbo].[TABLE_BOAT](
		[PKEY_BOATID] [BIGINT] IDENTITY(1,1) NOT NULL ,		
		[BOAT_NAME] [varchar](200) NOT NULL,
		[HOURLY_RATE] [INT]  DEFAULT 0,
		[IS_RENTED] [BIT] NOT NULL,			 
		CONSTRAINT [PK_tbl_EmployerGroup] PRIMARY KEY CLUSTERED 
		(
			[PKEY_BOATID] ASC
		)
		WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
	) ON [PRIMARY]
END 
GO


IF OBJECT_ID( N'[dbo].[TABLE_CUSTOMER]' , N'U' ) IS NULL
BEGIN
	CREATE TABLE [dbo].[TABLE_CUSTOMER](
		[ID] [BIGINT] IDENTITY(1,1) NOT NULL ,		
		[CUSTOMER_NAME] [VARCHAR](200) NOT NULL,
		[BOAT_ID] [BIGINT] NOT NULL
	) 
END 
GO